name = "Vanilla Farts"
author = "onkoe"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30145b064e468dc779515641686ccfc06f2f0d60b8fc504eee35a678f8d638e4"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
