name = "Vanilla Farts"
author = "onkoe"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38c7d96ec471c9af59c1df0b4da7f921ecbf89eadc345a70170a43aba4c2f5af"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
