name = "Vanilla Farts"
author = "onkoe"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c70d7d940c1bd5c89e5befe831b3bfc8d815a3d66a0b0f8cc33048fbd589973"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
