name = "Vanilla Farts"
author = "onkoe"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f8af8032b07c03602a82958ecb0b481d800601a582c33731b365ebeb7c201d8"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
